[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
verifi = "3JeB3GW3NoD3CcCi7MjKL7GTpqCgXcHDyEc247jAMiGs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/wba.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
